### ISSUE TITLE
security: first-generation cuid format deprecated

### ISSUE THREAD

**Issue by ericelliott** [xaevik/cuid.net#10]
Due to security concerns (which also exist in database auto-increment ids, uuid/guid, and most other id standrads), the Cuid standard is now deprecated in favor of [Cuid2](https://github.com/paralleldrive/cuid2).

**Comment by xaevik** [comment]
Hi @ericelliott, I appreciate the heads up on this change. I was in the process of getting ready to release 1.1 with some refactors. I'll migrate those into a 2.x releases and work on this instead.

**Comment by xaevik** [comment]
@ericelliott so I have mostly implemented the new format but there are a few items I'd like to just get some clarifications to ensure that release 2.x follows all the requirements. 

---

**Pseudo-random value**

In the second-generation implementation; you're generating entropy against a series of prime numbers. I'm guessing that was done as a means of generating a sufficiently secure random number without introducing another dependency.

For the .NET implementation I opted to use `System.Security.Cryptography.RandomNumberGenerator` ([ref](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator?view=net-6.0)) instead to generate an unsigned 64-bit integer value. It should be noted this implementation does increase the cost of instantiation from 44ms per one million objects to 127ms per one million objects from having to reference a cryptographically strong source.

https://github.com/xaevik/cuid.net/blob/b369381d267f1aaeb97628f45222ad2822303aca/src/cuid.net/Cuid.cs#L89-L100

If you would prefer the prime number implementation that returns an unsigned 32-bit integer, let me know.

---

**Session Counter**

Within the first-generation implementation currently present in the 1.x release, a static member was leveraged to keep track of the iterations:

https://github.com/xaevik/cuid.net/blob/85624d6c50b231642143b4c6c73a006c58993b66/src/cuid.net/Cuid.cs#L34
https://github.com/xaevik/cuid.net/blob/85624d6c50b231642143b4c6c73a006c58993b66/src/cuid.net/Cuid.cs#L350-L356

However, it appears that in the second-generation implementation, it is nothing more than a random 32-bit integer that is multiplied by a magic number. From my viewpoint that seems a bit contrary to the concept of a counter since there is no linear progression to it.

With that said, I have two options here. I can either implement the same behavior using the weaker `System.Random` ([ref](https://learn.microsoft.com/en-us/dotnet/api/system.random?view=net-6.0)) class (which I already use for prefix generation). Or I can opt for `DateTimeOffset.UtcTicks` ([ref](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.utcticks?view=net-6.0)) which tracks the number 100-interval nanoseconds that have occurred since 0001-01-01 00:00:00 UTC which should be sufficient to avoid collisions. This will of course introduce an additional penalty of 30ms per one million objects.

---

I appreciate any feedback you can provide on these items. There is also a performance bottleneck of high significance with hashing routine measuring in minutes per one million that I am still investigating. Once the numbers are down to reasonably acceptable levels, I'll release a preview of 2.x.

**Comment by ericelliott** [comment]
Thank you for the quick response on this, and thank you for the great questions!

> For the .NET implementation I opted to use System.Security.Cryptography.RandomNumberGenerator ([ref](https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.randomnumbergenerator?view=net-6.0)) instead to generate an unsigned 64-bit integer value. It should be noted this implementation does increase the cost of instantiation from 44ms per one million objects to 127ms per one million objects from having to reference a cryptographically strong source.

This is probably an improvement over the JavaScript implementation. The reason I used `Math.random()` in the JavaScript version is because there is no synchronous source of cryptographic randomness in the JavaScript specification that works in both browsers and Node, without introducing another dependency which could double the size of the JavaScript bundle.

> However, it appears that in the second-generation implementation, it is nothing more than a random 32-bit integer that is multiplied by a magic number. From my viewpoint that seems a bit contrary to the concept of a counter since there is no linear progression to it.

In the JavaScript implementation, we initiate the counter with a random number multiplied by a prime constant (`2057`). But after initialization, there is a linear progression to the counter.

Here's what happens when we log the counter value in the JS implementation:

```
createId(); // 1288
createId(); // 1289
createId(); // 1290
```

> Or I can opt for DateTimeOffset.UtcTicks ([ref](https://learn.microsoft.com/en-us/dotnet/api/system.datetimeoffset.utcticks?view=net-6.0)) which tracks the number 100-interval nanoseconds that have occurred since 0001-01-01 00:00:00 UTC which should be sufficient to avoid collisions. This will of course introduce an additional penalty of 30ms per one million objects.

The specification already calls for a timestamp entropy source. The counter needs to be an independent source of entropy in order to make a significant contribution to entropy.

**Comment by xaevik** [comment]
> In the JavaScript implementation, we initiate the counter with a random number multiplied by a prime constant (`2057`). But after initialization, there is a linear progression to the counter.

Yes, you are correct. I missed in the constructor that you are iterating the base counter. So, based on that I'll re-introduce the static counter member from 1.x but tweak the implementation to align with the current standard.

**Comment by xaevik** [comment]
@ericelliott the implementation is nearing completion, just still need to address the performance issues with it. Currently it is taking about 10 seconds per one million objects, and I feel I can get that number lower. 

I go into some detail as to what the bottlneck is [here](https://github.com/xaevik/cuid.net/pull/11#issuecomment-1368288961) but what it comes down to is that the SHA-512 checksum must be converted from a byte array to a `BigInteger` and C# does not really have native facilities for converting integers into other base types.

I'll keep you in the loop if you're interested.

**Comment by xaevik** [comment]
@ericelliott I hope you don't mind, but I have one final item for this implementation that I am hoping you can help me with. It has to do with the fingerprint being generated for the `cuid2` objects.

For first-generation `cuid` objects, the fingerprint comprised of the last two digits of the current threaded process identifier and the last two characters of the system hostname (base36 encoded), obviously this was due to the size constraints.

However, for the second-generation implementation, I would prefer to go with something a bit more concrete.

What presents a problem for this implementation is what source(s) should be chosen for the generation of the fingerprint. As this library can run on a wide range of platforms and architectures, the availability of which sources can vary (for instance iOS does not allow direct access to MAC address information). 

Finally, there is also the possibility that this library will be called from a scope where it may be running on one of the platforms, but it is in a highly isolated state (such as an Azure App Function Isolated Worker), which means a fallback should be chosen should the source(s) not be available.

The only target I do not feel would be a problem is Blazor WASM. Since it is a WebAssembly artifact, the Browser's global object keys could be used the same way the JavaScript implementation does it.

I look forward to hearing your thoughts on this.

**Comment by ericelliott** [comment]
I don’t know enough about your environment constraints to give a definitive answer, so I will say what you want to look for, instead:

Host uniqueness is is the most important thing. hostname + pid would likely be ok. More entropy is obviously better. More than 24 bytes of entropy, and ideally 32 would be great if you can find it, but less is not a deal breaker. Fall back on random entropy if you can’t reliably fill the space.

**Comment by xaevik** [comment]
Fair enough, I should be able to find enough non-privileged unique sources to build something about that length. Sans that I'll fall back to `RandomNumberGenerator`.

Just as a point of disclosure I personally am not using this in any production infrastructure at this time (though it is planned for a few microservices). The general idea was just to build something to supersede the `NCuid` project for which has seen no maintenance in the last 8 years.
